#Title
title: "Virus Epidemiology and Control Group"

# The slogan describes the website and is used on homepage in <title> and other important places
slogan: "Virus Epidemiology and Control"

# The description is used on homepage and in the footer to quickly describe the website. Use a maximum of 150 characters for SEO-purposes.
description: "We conduct research into population dynamics of viral pathogens" 

# Main author of the website
# See > authors.yml
author: virec-group

# This URL is the main address for absolute links. Don't include a slash at the end.
url: ''
baseurl: ''
